name: fakestore-backend-drf
services:
  app:
    image: eduardosilvasc/fakestore-backend-drf:latest
    environment:
      - MODE=DEVELOPMENT #  possible values are: DEVELOPMENT, PRODUCTION, MIGRATE
      - SECRET_KEY=8v_mxd@ntv%r3ynr(*nn35fl-9&_%^(=t4*kqc8#y@*#@+4xe8
      - DEBUG=True #  possible values are: True, False
      - PASSAGE_APP_ID=jwi7hT7o7cfHOjvhGVa622sN
      - PASSAGE_API_KEY=v1o0jVqjZ0.TYRRxfLvspWl76G3uf7cf9n6u4UQdfS73QyXRMnZwSoi70dg1QLBWPLC2NEI0cDr
    ports:
      - 8000:8000
